### ISSUE TITLE
capturePerformanceReport is no longer on driver

### ISSUE THREAD

**Issue by jeremiahlukus** [VeryGoodOpenSource/very_good_performance#20]
<img width="828" alt="Screen Shot 2021-11-30 at 9 13 46 PM" src="https://user-images.githubusercontent.com/17206638/144159469-914bd955-8132-4dc3-8f46-7e6621ca3d7a.png">

**Comment by jeremiahlukus** [comment]
I think capturePerformaceReport was moved to traceAction per 
https://docs.flutter.dev/cookbook/testing/integration/profiling  

Once i figure out how to get it running ill submit a PR

**Comment by jorgecoca** [comment]
@jeremiahlukus just to double check, did you include 

```dart
import 'package:very_good_performance/very_good_performance.dart';
```

in your file?

`capturePerformanceReport` is an extension method, so you still need to include the right imports.

This example might help: https://github.com/VeryGoodOpenSource/very_good_performance/blob/main/example/e2e/counter_test.dart

**Comment by jeremiahlukus** [comment]
@jorgecoca are you able to run these with flavors? 

Copy pasting that example i get a ton of 

```
Error: Not found: 'dart:ui'
import 'dart:ui' as ui;
       ^
```
due to https://github.com/VeryGoodOpenSource/very_good_performance/blob/main/example/e2e/e2e.dart#L6

**Comment by jorgecoca** [comment]
Yes, you can run `flutter drive` with flavors (you can run `flutter drive --help` from your terminal to see how).

How are you running these tests?

**Comment by jeremiahlukus** [comment]
If i remove that line and put what the flutter docs say 

i get 
```
DriverError: Could not determine URL to connect to application.
  Either the VM_SERVICE_URL environment variable should be set, or an explicit URL should be provided to the FlutterDriver.connect() method.
 ```
 
 i am running the tests like 
 `flutter drive --driver=test_driver/driver_test.dart --target=integration_test/counter_profile_test.dart --flavor development` 
 
 
 driver_test:
 ```dart
 import 'package:flutter_driver/driver_extension.dart';
import 'package:flutter_template/main_development.dart' as app;

void main() {
  enableFlutterDriverExtension();
  app.main();
}
```
 
 The tests are copy paste
