### ISSUE TITLE
Support additional metrics

### ISSUE THREAD

**Issue by KyleFin** [VeryGoodOpenSource/very_good_performance#23]
If I understand correctly this library currently only measures frame rate performance, right? (How much time is spent building / rendering each frame.)

It could also be extended to include metrics like:
- [Memory usage](https://github.com/flutter/flutter/wiki/How-to-write-a-memory-test-for-Flutter)
- [CPU / GPU](https://github.com/flutter/flutter/blob/51bb11f7cece47840a9ee6d6d43db97ab16b31df/dev/devicelab/lib/tasks/perf_tests.dart#L409) usage
- Battery usage(? Possibly with CPU / network usage as proxies)

**Comment by BeatriceMitchell** [comment]
Since this package is not actively used, we are going to archive it.
